// <auto-generated />
namespace TayanaYachtMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddYachtDimensions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddYachtDimensions));
        
        string IMigrationMetadata.Id
        {
            get { return "202603260701438_AddYachtDimensions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
